apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lunchorder-dev

resources:
  - ../../base

# Override namespace cho dev
patches:
  # Scale down replicas trong dev
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: backend
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: frontend

# Override ConfigMap cho dev
configMapGenerator:
  - name: lunchorder-config
    behavior: merge
    literals:
      - APP_ENV=development

# Đặt tên image dev
images:
  - name: ghcr.io/anab821/lunchorder-backend
    newTag: dev
  - name: ghcr.io/anab821/lunchorder-frontend
    newTag: dev
